[client]
showSidebarNavigation = false

[theme]
primaryColor = "#B71C1C"
backgroundColor = "#FDF6F6"
secondaryBackgroundColor = "#F5EAEA"
textColor = "#2E2E2E"
font = "sans serif"

[theme.sidebar]
primaryColor = "#D32F2F"               
backgroundColor = "#F2DCDC"            
secondaryBackgroundColor = "#E8C8C8"   
textColor = "#2E2E2E"