[api]
model = "API_URL"

[gcp_credentials]
type = "authorized_user"
client_id = "YOUR-CLIENT-ID.apps.googleusercontent.com"
client_secret = "YOUR-CLIENT-SECRET"
refresh_token = "YOUR-REFRESH-TOKEN"
quota_project_id = "PROJECT-ID"
universe_domain = "googleapis.com"

[bigquery]
dataset = "BIGQUERY-DATASET"